#!/bin/sh
# postinst script for oracle-base-rdbms
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

#DEBHELPER#

postinst "debian" "$@"

_attr() {
  flags="${4:-}"
  chown $flags "$2" "$3" && chmod $flags "$1" "$3"
}

case "$1" in
    configure)
        # Set filesystem rights
        dpkg -L oracle-base-rdbms | while read line ; do
            [ -f $line ] && continue
            case "$line" in
              /var/log/oracle/* ) _attr 2770 oracle:dba $line ;;
              /usr/bin/* ) _attr 750 oracle:dba $line ;;
              /db ) _attr 775 oracle:dba $line ;;
            esac
        done
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    null)
        exit 0
    ;;
    *)
        echo "postinst called with unknown argument \`$@'" >&2
        exit 1
    ;;
esac

exit 0
