#!/bin/sh
# postrm script for oracle-base-rdbms
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

#DEBHELPER#

postrm "debian" "$@"

_attr() {
  flags="${4:-}"
  chown $flags "$2" "$3" && chmod $flags "$1" "$3"
}

case "$1" in
  purge) _attr 2775 oracle:oracle /etc/oracle -R ;;
esac

exit 0


